### ISSUE TITLE
Killercoda configmap example: redis.conf fix

### ISSUE THREAD

**Issue by lurodrig** [chadmcrowell/CKA-Exercises#8]
Hey @chadmcrowell 

Thank you very much for your examples on killercoda, very useful!

Just a minor comment regarding the `configmap` one [1] I would change the name of the config file in the data section and remove the `:` from the memory settings (as specified in the redis docs [2]):
```
apiVersion: v1
data:
  redis.conf: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: redis-config
```
In this way it matches with the redis arg in the `command` section of the `redis-pod`: 
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-pod
  name: redis-pod
spec:
  containers:
  - command:
    - redis-server
    - /redis-master/redis.conf
    image: redis:7
    name: redis-pod
    volumeMounts:
      - name: config-volume
        mountPath: /redis-master
    ports:
    - containerPort: 6379
  volumes:
    - name: config-volume
      configMap:
        name: redis-config
```
And the redis container picks up the memory settings:
```
$ kubectl exec -it redis-pod -- /bin/bash
root@redis-pod:/data# cat /redis-master/
..2024_09_09_17_00_40.2749132822/ ..data/                           redis.conf                        
root@redis-pod:/data# cat /redis-master/redis.conf 
maxmemory 2mb
maxmemory-policy allkeys-lru
root@redis-pod:/data# redis-cli 
127.0.0.1:6379> CONFIG GET maxmemory
1) "maxmemory"
2) "2097152"
127.0.0.1:6379> CONFIG GET maxmemory-policy
1) "maxmemory-policy"
2) "allkeys-lru"
```

Cheers,

Luis

[1] https://killercoda.com/chadmcrowell/course/cka/configmaps
[2] https://redis.io/docs/latest/operate/oss_and_stack/management/config/
